name: Run Script on File Rename

on:
  push:
    paths:
      # - '**/*'
      - 'databank/content/**'

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    # - name: Check for file rename
    #   id: check_rename
    #   run: |
    #     if [[ -n "$(git diff --name-status ${{ github.sha }}^ -- ${{ github.sha }})" ]]; then
    #       echo "::set-output name=files_changed::true"
    #     else
    #       echo "::set-output name=files_changed::false"
    #     fi


    - name: Grant execute permissions to the script
      run: chmod +x $GITHUB_WORKSPACE/automation/aws-post-trigger-sitemap.sh


    - name: Run script which calls lambda function
      # if: steps.check_rename.outputs.files_changed == 'true'
      run: |
        # script link automation folder at root
        automation/aws-post-trigger-sitemap.sh
