name: Run Script on File Rename

on:
  push:
    paths:
      # - '**/*'
      - 'databank/content/**'

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    # - name: Check for file rename
    #   id: check_rename
    #   run: |
    #     changed_files=$(git diff --name-status "${{ github.event.before }}" "${{ github.sha }}")
    #     if [[ -n "$changed_files" ]]; then
    #       echo "::set-output name=files_changed::true"
    #     else
    #       echo "::set-output name=files_changed::false"
    #     fi

    - name: Run script which calls lambda function
      # if: steps.check_rename.outputs.files_changed == 'true'
      run: |
        # script link automation folder at root
        automation/aws-post-trigger-sitemap.sh
